<?php

namespace App\Filament\Pages;

use App\Filament\Widgets\ProductList;
use Filament\Pages\Page;

class Products extends Page
{
    protected static ?string $navigationIcon = 'heroicon-o-document-text';

    protected static string $view = 'filament.pages.products';

    protected function getHeaderWidgets(): array
    {
        return [ProductList::class]; // TODO: Change the autogenerated stub
    }


}
